version: 0.0.{build}
os:
  - Visual Studio 2022
clone_depth: 1
branches:
  only:
    - dcmqi
skip_tags: true
clone_folder: c:\ITK
configuration:
  - Release
platform:
  - x64
environment:
  PYTHON_DIR: "C:\\Python311-x64"
  PATH: "%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"
  GITHUB_TOKEN:
    secure: mnRPU2KJBMkkUa4fo4ebLpsEG/gYpcAy4/X2ihGiwZiPGpkyvF1ItFFRSlUGubvf
  APPVEYOR_API_TOKEN:
    secure: 3+wBc5SxNqx3XjsY3EZ7afvQbLAWWcw30SPGK7q+QPA=
before_build:
  - cmd: cmake --version
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/QIICR/zlib-dcmqi/releases/download/zlib-dcmqi-1.2.3-VS17-Win64-Release-static/zlib-dcmqi.zip", "C:\zlib-dcmqi.zip")
  - cmd: 7z x C:\zlib-dcmqi.zip -oC:\zlib-install
  - cmd: dir c:\zlib-install
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/QIICR/dcmtk-dcmqi/releases/download/DCMTK-dcmqi-3.6.7_20220105-VS12-Win64-Release-v0.0.32-static/DCMTK-dcmqi.zip", "C:\DCMTK-dcmqi.zip")
  - cmd: 7z x C:\DCMTK-dcmqi.zip -oC:\DCMTK-install
  - cmd: dir c:\DCMTK-install
  - cmd: mkdir c:\ITK\ITK-build
  - cmd: mkdir c:\ITK-install
  - cmd: cd c:\ITK\ITK-build
  - cmd: cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:STRING=Release -DITK_USE_SYSTEM_ZLIB:BOOL=ON -DZLIB_ROOT:PATH=c:\zlib-install -DZLIB_INCLUDE_DIR:PATH=c:\zlib-install\include -DZLIB_LIBRARY:FILEPATH=c:\zlib-install\lib\zlib.lib -DDCMTK_DIR:STRING=C:\DCMTK-install\cmake -DBUILD_TESTING:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DITK_BUILD_DEFAULT_MODULES:BOOL=OFF -DITKGroup_Core:BOOL=ON -DITK_GroupFiltering:BOOL=ON -DModule_ITKIOXML:BOOL=ON -DModule_ImageStatistics:BOOL=ON -DModule_LabelMap:BOOL=ON -DITK_GroupIO:BOOL=ON -DModule_MGHIO:BOOL=OFF -DITK_INSTALL_NO_DEVELOPMENT:BOOL=OFF -DKWSYS_USE_MD5:BOOL=ON -DITK_WRAPPING:BOOL=OFF -DITK_WRAP_PYTHON:BOOL=OFF -DCMAKE_INSTALL_PREFIX=c:\ITK-install -DBUILD_SHARED_LIBS:BOOL=OFF C:\ITK

build_script:
  - cmd: type ITK.sln
  - cmd: msbuild ITK.sln /m
  - cmd: msbuild INSTALL.vcxproj
  - ps: Copy-Item c:\ITK-install -Destination c:\ITK\ITK-install -Recurse
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
artifacts:
  - path: ITK-install
    name: ITK-dcmqi
    type: zip
deploy:
  release: ITK-dcmqi-VS17-Win64-Release-v$(appveyor_build_version)-static
  description: 'ITK slicer-v5.3rc04-2022-09-19-62eb5ca'
  provider: GitHub
  auth_token:
    secure: ES/eqjQ0Yw+SY//wQdGB5zdHAqcAZDj75EzYjnvaibQa4LfjYaj4tWltthhvoiWe
  artifact: ITK-dcmqi
  draft: false
  prerelease: false
  on:
    branch: dcmqi
    APPVEYOR_REPO_TAG: false
