version: 0.0.{build}
os:
  - Visual Studio 2013
clone_depth: 1
branches:
  only:
    - dcmqi
skip_tags: true
clone_folder: c:\ITK
install:
  - cinst cmake
configuration:
  - Release
platform:
  - x64
before_build:
  - cmd: cmake --version
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/zlib/releases/download/zlib-dcmqi-1.2.3-VS12-Win64-Release/zlib-dcmqi.zip", "C:\zlib-dcmqi.zip")
  - cmd: 7z x C:\zlib-dcmqi.zip -oC:\zlib-build
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/DCMTK/releases/download/DCMTK-dcmqi-3.6.1_20160216-VS12-Win64-Release/DCMTK-dcmqi.zip", "C:\DCMTK-dcmqi.zip")
  - cmd: 7z x C:\DCMTK-dcmqi.zip -oC:\DCMTK-build
  - cmd: mkdir c:\ITK\ITK-build
  - cmd: cd c:\ITK\ITK-build
  - cmd: cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE:STRING=Release -DZLIB_ROOT:STRING=C:\zlib-build -DDCMTK_DIR:STRING=C:\DCMTK-build C:\ITK
build_script:
  - cmd: type ITK.sln
  - cmd: msbuild ITK.sln /m
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
artifacts:
  - path: ITK-build
    name: ITK-dcmqi
    type: zip
deploy:
    release: ITK-dcmqi-VS12-Win64-Release
    provider: GitHub
    description: 'ITK packaged by appveyor for dcmqi'
    artifact: ITK-dcmqi
    auth_token:
      secure: ffHRHxe8buygkDl6kRw4vaNaH/ikYGoDn3TXfZ42cFXq7986houCT7/7qB8o5Vvf
